Service List finalized
openBackhaul/MacAddressTableRecorder pull request #18
Opened 2022-09-22 09:08 UTC by kurzkama

Service List finalized

2022-09-22 09:10 UTC, kurzkama commented
Service List for MATR finalized

2022-09-22 12:14 UTC, kmohr-soprasteria commented
Hier meine Review-Findings.

---
**1. ProfileInstances**  
- für die Bearbeitung sollte ein eigener Issue mit eigenem Branch (und Pull Request) erstellt werden (Zwischenergebnisse dann auch in dem Branch committen)
- /v1/configure-MAC-polling-intervall -> typo: interval nur mit einem l
- UUIDs: Sequence-Nummer-Teil soll nur 3 Zeichen lang sein (müsste also statt *p-1000, z.B: *p-100 sein)
- unten sind noch die unbenutzten templates drin: die sollen laut Anleitung gelöscht werden: *Finally, just delete the form that waits for completion*

---
**2. ServiceList**
- hier auch */v1/configure-MAC-polling-intervall* -> interval mit nur einem l
- uuids passen noch nicht
  - zB: uuid: *matr-1-0-0-op-s-1001* --> müsste eigentlich gemäß der Anleitung so aussehen: *matr-1-0-0-op-s-is-<3stellige SequenceNumber>*
  - auch bei den schon vorgegebenen uuids müssen die Anpassungen noch vorgenommen werden, die scheinen alle noch dem alten Schema zu
  - doppelte uuids: dein erster Service müsste um eins verschoben anfangen, bei der ersten uuid fehlt vorne zwar die OwnApplicationID, aber die muss man sich in dem Fall dazu denken 

```
individual: 
   - service-name: /v1/start-application-in-generic-representation
   uuid: op-s-3000		(1)
        
   - service-name: /v1/provide-mac-table-of-device
   uuid: matr-1-0-0-op-s-3000	(2)

korrekt wären die uuids:
1) matr-1-0-0-op-s-is-300
2) matr-1-0-0-op-s-is-301
```

---
```
##provide mactable: device/interface/VLAN/mac-address (Question: one device per request or several)
- service-name: /v1/provide-trace-of-mac-address
```
Da kann man in der OAS später definieren, welche Input-Parameter man akzeptiert (in deinem Fall wären das dann Query-Parameter - d.h. die würden beim Aufruf mit ?<parameter-infos> an die URL angehängt werden): da kannst du dann definieren, ob du entweder nur ein Device als Input akzeptierst oder eine Liste (wenn man das z.B. als Liste mit Komma als Trennzeichen macht, wäre ein einzelnes Device quasi wie eine Input-Liste mit nur einem Eintrag)  

---
``` ##usecase: List all devices/interfaces, that have the same mac-address in their mactable as the device sent in the request.```
warum ist das noch auskommentiert?   
 
---
Vorschlag: einen Service, der alle Daten aus der internen Datenbank zurückliefert anbieten (s. auch unten für Datenübergabe an newRelease)

---
```
  http-server:
    own-application-name: MacAddressTableRecorder
    own-release-number: 1.0.0
    uuid: http-s-0000
  tpc-server:
    own-ip-address: 10.118.125.157
    own-tcp-port: 2004
    uuid: tcp-s-0000
```
- Da muss eine Fake-IP-Adresse + Port angegeben werden: [s. hier](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/TestingApplications/Infrastructure/SdnLaboratory/IpAddresses/IpAddresses.md)
- Für dich wäre das die IP 1.1.4.5, mit TCP-Port 4005
- bei den anderen http-clients müssten IP-Adresse + Port glaube ich auch gemäß der Liste je Application geändert werden (also z.B. der http-Client Eintrag für das RegistryOffice hätte dann gemäß der Liste 1.1.3.1 und 3001). Ich bin mir aber nicht ganz sicher (sollten wir Thorsten nochmal fragen).

---
http-client für NewRelease:
- wenn du beim Einspielen des neuen Releases irgendwelche Daten aus dem alten Release behalten willst, müsstest du hier unter operation-clients/own-oam/individual die Services (von oben) angeben, die Daten übergeben sollen. 
- Laut Thorstens Beschreibung wird im MATR eine interne Datenbank benutzt. Es wäre gut, wenn die dann übergeben würde. 
- Ich hab oben ja vorgeschlagen einen Service anzulegen, der alle Daten aus der internen Datenbank zurückliefert. Theoretisch müsste man dann eigentlich nur den hier angeben und dann müsste alles ins neue Release übernommen werden.

---
http-client Block für MWDI:
- Deine Application hat eine Dependency zum MicroWaveDeviceInventory/MWDI, deshalb brauchst du dafür auch einen eigenen http-client Block. Da musst du dann imho die Services angeben, die du vom MWDI benutzen willst.
- Du musst mindestens mal die Liste der Devices vom MWDI abrufen: da hab ich bei mir folgenden Service für vorgesehen: */v1/provide-list-of-mwdi-mount-names*

2022-09-22 12:14 UTC, kmohr-soprasteria requested changes
siehe Kommentar

2022-10-04 13:41 UTC, kmohr-soprasteria commented
Die profileInstances sind auch in dem anderen Pull-Request. Es ist besser, wenn es nur ein Pull-Request für die Änderungen an der selben Datei gibt. (ggf. muss nach dem Merge des einen Pull-Requests erst eine Synchronisation des zweiten Branches vor dem Merge erfolgen, so wie wir das letzten Freitag gemacht hatten).
____
Review für die Service List in eigenem Kommentar

2022-10-04 13:53 UTC, kmohr-soprasteria requested changes
sieht im Prinzip schon ganz gut aus, aber ein paar Sachen sind mir noch aufgefallen (s. Kommentare)

2022-10-04 15:03 UTC, kmohr-soprasteria commented
Achtung Korrektur: ich hatte oben bei den http-clients einen Fehler gemacht.
Die uuids müssen auch noch die Infos zur TargetApplication drin haben, z.B.: xx-1-0-0-op-c-bm-eatl-1-0-0-000

Das würde bei dir bedeuten, wenn du z.B. auf das mwdi zugreifen willst: statt *uuid: mwdi-1-0-0-http-s-00000*
müsste da dann sowas stehen wie:
[deine-App]-http-c-[serviceType]-[targetApp]-[num], also z.B.
```
        individual:
          - service-name: /v1/provide-list-of-mwdi-mount-names
            uuid: matr-1-0-0-http-c-is-mwdi-1-0-0-001
```

Wenn man das z.B. mit dem Eintrag im Template für das OperationKeyManagement vergleich, käme man für den ganzen Block dann auf sowas:
```
  - http-client:
      application-name: MicroWaveDeviceInventory
      release-number: 1.0.0
      uuid: matr-1-0-0-http-c-is-mwdi-1-0-0-000
    tcp-client:
      ip-address: [ip vom mwdi]
      tcp-port: [port vom mwdi]
      uuid: matr-1-0-0-tcp-c-is-mwdi-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
      service:
        basic:
        individual:
          - service-name: /v1/provide-list-of-mwdi-mount-names
            uuid: matr-1-0-0-http-c-is-mwdi-1-0-0-001
```

2022-10-21 08:11 UTC, kurzkama commented
Updated:
Fake IP´s und Release Nummern nach aktuellem Application Pattern

Open:
- mdi client
- elasic search client

Ich würde das gerne ohne die offenen Punkte nach develop mergen.

2022-11-22 13:37 UTC, kmohr-soprasteria commented on MacAddressTableRecorder+services.yaml
> +          uuid: matr-1-0-0-op-s-bs-004
es gibt einen neuen Service-Eintrag, der ergänzt werden muss:
        - service-name: /docs
          uuid: xx-1-0-0-op-s-bs-005

2022-11-22 13:40 UTC, kmohr-soprasteria commented on MacAddressTableRecorder+services.yaml
es gab auch ein update für die TCP-Server:
  tcp-server:
    - description: Without TLS layer
      local-protocol: http
      own-ip-address: ## TODO: Add OwnIpAddress
      own-tcp-port: ## TODO: Add OwnTcpPort
      uuid: xx-1-0-0-tcp-s-bm-000
    - description: With TLS layer
      local-protocol: https
      own-ip-address: ## TODO: Add OwnIpAddress
      own-tcp-port: ## TODO: Add OwnTcpPort
      uuid: xx-1-0-0-tcp-s-bm-001

2022-11-22 13:42 UTC, kmohr-soprasteria commented on MacAddressTableRecorder+services.yaml
>    - http-client:
für das Registry-Office gibt es jetzt einen v2.0.0 Release, der http-client muss aktualisiert werden

2022-11-22 13:42 UTC, kmohr-soprasteria commented on MacAddressTableRecorder+services.yaml
>    - http-client:
beim TypeApprovalRegister gibt es auch v2.0.0

2022-11-22 13:43 UTC, kmohr-soprasteria commented on MacAddressTableRecorder+services.yaml
EATL analog v2.0.0

2022-11-22 13:45 UTC, kmohr-soprasteria commented on MacAddressTableRecorder+services.yaml
> +## TODO mdi client to be adopted
die MWDI-App ist auch aktualisiert, kann hier also auch befüllt werden.

2022-11-22 13:46 UTC, kmohr-soprasteria commented on MacAddressTableRecorder+profileInstances.yaml
>  profile-instances:
hier gab es ein Update im Template, die Einträge müssten aktualisiert werden.

2022-11-22 13:46 UTC, kmohr-soprasteria requested changes
s. Kommentare in den Files

2023-04-05 14:23 UTC, merged