Kurzkama/issue17
openBackhaul/MacAddressTableRecorder pull request #19
Opened 2022-09-29 09:58 UTC by kurzkama

ProfileInstances and profiles updated with newest template

2022-10-04 13:38 UTC, kmohr-soprasteria reviewed
In the profile list there are entries for FileProfile and StringProfile, but in the profileInstancesList there are no corresponding entries.
Is the profileInstances list not yet complete? If it is, the unused profiles should be removed from the profileList. (Or if you would like to keep them for possible later usage, they also could be commented out.)

2022-10-21 08:25 UTC, kurzkama commented
Deleted FileProfile and StringProfile

2022-11-22 13:47 UTC, kmohr-soprasteria commented on MacAddressTableRecorder+profiles.yaml
>  profiles:
das Template wurde aktualisiert, die Einträge hier müssen entsprechend angepasst werden.

2022-11-22 13:48 UTC, kmohr-soprasteria commented on MacAddressTableRecorder+profileInstances.yaml
>  profile-instances:
hier bitte auch die Neuerungen vom Template übernehmen

2022-11-22 13:48 UTC, kmohr-soprasteria requested changes
Templates wurden zwischenzeitlich aktualisiert, bitte die Files hier auch anpassen

2023-04-05 14:27 UTC, kurzkama commented
Pull-request outdated. Data was included in '#17

2023-04-05 14:27 UTC, closed without merging